/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AntijnvanderGun (https://sketchfab.com/AntijnvanderGun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ww1-plane-c4edeb0e410f46e8a4db320879f0a1db
Title: Stylized WW1 Plane
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import planeScene from "@assets/3d/plane.glb"
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";

const Plane: React.FC<{ isRotating: boolean } & typeof planeScene> = ({ isRotating, ...props }) => {
  const ref = useRef<typeof planeScene>();
  const { scene, animations } = useGLTF(planeScene) as GLTF;
  const {actions} = useAnimations(animations, ref)

  useEffect(() => {
    if (isRotating) {
        actions['Take 001']?.play()
    } else {
        actions['Take 002']?.stop()
    }
  }, [actions, isRotating])

  return (
    <mesh {...props} ref={ref}>
        <primitive object={scene} />
    </mesh>
  );
}

export default Plane